// Stringhe UI del wizard e della dashboard (IT/EN).
// TypeScript garantisce che l'inglese abbia le stesse chiavi dell'italiano.
import type { Locale } from "@/lib/i18n";
import type { ObligationStatus, RiskLevel } from "./types";

const it = {
  kicker: "AI Act Compliance Checker · beta",
  introTitle: "Classifica il rischio AI Act di un tuo sistema, in 10 minuti.",
  introBody:
    "Un questionario guidato ti porta alla classificazione del rischio secondo il Regolamento (UE) 2024/1689 (AI Act), con la checklist degli obblighi applicabili, i gap e un piano d'azione. Ogni esito cita la base normativa: nessuna intelligenza artificiale generativa, solo regole deterministiche verificabili.",
  introBullets: [
    "Un sistema AI alla volta (ripetibile per ogni sistema).",
    "Le risposte restano nel tuo browser finché non scegli tu di salvarle nel tuo account.",
    "Aggiornato alle modifiche dell'Omnibus digitale (giugno 2026), con avvertenze dove non ancora in Gazzetta Ufficiale.",
  ],
  start: "Inizia la valutazione",
  stepLabel: (n: number, total: number) => `Passo ${n} di ${total}`,
  back: "← Indietro",
  next: "Avanti",
  seeResult: "Vedi il risultato",
  backHome: "← ComplyAI",
  myAssessments: "Le mie valutazioni →",

  s1Title: "Il sistema e il tuo ruolo",
  s1Name: "Nome del sistema AI (come lo chiamate in azienda)",
  s1NamePh: "Es. screening CV con AI, chatbot assistenza clienti…",
  s1Desc: "Cosa fa, in una frase (opzionale)",
  s1RoleLegend: "Qual è il ruolo della tua azienda rispetto a questo sistema?",
  s1RoleNote: "Definizioni: art. 3, punti 3–4 AI Act. Il ruolo determina quali obblighi si applicano.",
  roles: {
    deployer: { label: "Lo usiamo (deployer)", desc: "Utilizziamo un sistema AI sviluppato da altri, sotto la nostra autorità." },
    provider: { label: "Lo sviluppiamo/forniamo (provider)", desc: "Sviluppiamo il sistema e lo immettiamo sul mercato o in servizio con il nostro nome/marchio (anche solo per uso interno)." },
    both: { label: "Entrambi", desc: "Lo abbiamo sviluppato e lo usiamo noi stessi." },
  },

  s2Title: "Pratiche vietate",
  s2Body: "Il sistema svolge una di queste pratiche? Sono vietate dal 2 febbraio 2025 (art. 5 AI Act), a prescindere da tutto il resto.",
  s2None: "Nessuna di queste pratiche",

  s3Title: "Prodotti regolamentati (Annex I)",
  s3Body: "Il sistema è un prodotto — o un componente di sicurezza di un prodotto — già soggetto a normativa UE armonizzata (dispositivi medici, giocattoli, ascensori, apparecchiature radio, veicoli, macchinari…)?",
  annexI: {
    no: { label: "No", desc: "Il sistema non fa parte di prodotti soggetti a normativa UE di prodotto." },
    sectionA: { label: "Sì, un prodotto regolamentato", desc: "Es. dispositivo medico, giocattolo, ascensore, apparecchiatura radio (Annex I, sez. A)." },
    machinery: { label: "Sì, un macchinario", desc: "Prodotto soggetto al Regolamento Macchine (UE) 2023/1230 — regime speciale post-Omnibus." },
    unsure: { label: "Non lo so", desc: "Segnaleremo di verificarlo: cambia scadenze e obblighi." },
  },
  s3Carveout: "L'AI svolge solo funzioni di assistenza, ottimizzazione, comfort o controllo qualità",
  s3CarveoutDesc: "…e un suo malfunzionamento non metterebbe in pericolo salute o sicurezza (definizione ristretta di «componente di sicurezza», Omnibus).",

  s4Title: "Casi d'uso ad alto rischio (Annex III)",
  s4Body: "Il sistema è usato in una di queste aree? (Obblighi dal 2 dicembre 2027, salvo deroghe — le vediamo al passo successivo.)",
  s4None: "Nessuna di queste aree",

  s5Title: "Possibili deroghe (art. 6(3))",
  s5Body: "Un sistema in area Annex III può non essere ad alto rischio se ricorre una di queste condizioni. Attenzione: è un'autovalutazione da documentare, e la profilazione la esclude sempre.",
  s5None: "Nessuna condizione applicabile",
  s5Profiling: "Il sistema effettua profilazione di persone fisiche",
  s5ProfilingDesc: "Valutazione automatizzata di aspetti personali (rendimento, affidabilità, interessi, comportamento…). Se sì, la deroga non si applica mai (art. 6(3), ultimo comma).",

  s6Title: "Trasparenza (art. 50)",
  s6Body: "Questi obblighi si applicano dal 2 agosto 2026 e l'Omnibus NON li ha rinviati. Il sistema rientra in uno di questi casi?",
  s6None: "Nessuno di questi casi",

  s7Title: "Ultima domanda e riepilogo",
  s7Gpai: "Sviluppiamo un modello di AI per finalità generali (GPAI)",
  s7GpaiDesc: "Cioè un modello di base (es. un LLM addestrato da voi) fornito a terzi — raro per una PMI: usare ChatGPT/Claude non ti rende provider GPAI.",
  s7Summary: "Riepilogo risposte",
  s7System: "Sistema",
  s7Unnamed: "(senza nome)",
  s7Role: "Ruolo",
  s7Prohibited: "Pratiche vietate selezionate",
  s7CarveoutShort: "(solo funzioni non di sicurezza)",
  s7Areas: "Aree Annex III",
  s7Exemptions: "Deroghe 6(3)",
  s7Profiling: "Profilazione",
  s7Transparency: "Casi di trasparenza art. 50",
  yes: "sì",
  no: "no",

  reportTitle: "ComplyAI — AI System Risk Assessment Report",
  generatedOn: "Generato il",
  evaluatedSystem: "Il sistema valutato",
  roleLabel: "Ruolo",
  bothRoles: "provider e deployer",
  whyTitle: "Perché questo esito",
  deadlinesTitle: "Date rilevanti per te",
  thWhen: "Quando",
  thWhat: "Cosa",
  thSource: "Fonte",
  pendingGu: "In attesa di pubblicazione in GU UE",
  checklistTitle: "Checklist degli obblighi",
  checklistHint: "Indica lo stato attuale di ciascun obbligo: gap e piano d'azione si aggiornano di conseguenza.",
  dueBy: "entro",
  alreadyApplicable: "già applicabile",
  planTitle: (n: number) => `Piano d'azione (${n} elementi)`,
  planEmpty: "Nessun gap: tutti gli obblighi risultano conformi o non applicabili.",
  ownerLabel: "Responsabile (owner)",
  ownerPh: "Es. Resp. IT, HR, titolare…",
  dueLabel: "Scadenza interna",
  duePh: "Es. 30/09/2026",
  warningsTitle: "Avvertenze",
  reportFooterNote: "* = data derivante dall'Omnibus, in attesa di pubblicazione in GU UE.",
  sourcesNote: "Contenuti normativi:",
  printBtn: "Stampa / salva PDF",
  jsonBtn: "Scarica dati (JSON)",
  restartBtn: "Nuova valutazione",

  levels: {
    prohibited: "Pratica vietata",
    high: "Alto rischio",
    transparency: "Rischio limitato — obblighi di trasparenza",
    minimal: "Rischio minimo",
  } as Record<RiskLevel, string>,
  statuses: {
    ok: "Conforme",
    partial: "Parziale",
    missing: "Mancante",
    unknown: "Da valutare",
    na: "Non applicabile",
  } as Record<ObligationStatus, string>,

  // --- Account / salvataggio (Sprint 1.2) ---
  saveTitle: "Salva nel tuo account",
  saveHint: "Gratuito. Ritrovi le valutazioni, le aggiorni e ogni modifica finisce nel registro audit.",
  saveBtn: "Salva questa valutazione",
  updateBtn: "Aggiorna valutazione salvata",
  savedOk: "Salvata ✓ — la ritrovi in «Le mie valutazioni».",
  saveErr: "Salvataggio non riuscito:",
  notConfigured: "Il salvataggio sarà disponibile a breve (backend in configurazione). Intanto usa Stampa/PDF o JSON.",
  authEmail: "Email",
  authPassword: "Password (min 6 caratteri)",
  authSignIn: "Accedi",
  authSignUp: "Registrati",
  authOr: "oppure",
  authHint: "Nessuna email di conferma in fase beta: registrati e sei dentro.",
  authErr: "Autenticazione non riuscita:",
  signOut: "Esci",
  loading: "Caricamento…",

  dashTitle: "Le mie valutazioni",
  dashEmpty: "Nessuna valutazione salvata. Completa il questionario e salvala dal report.",
  dashOpen: "Apri",
  dashDelete: "Elimina",
  dashConfirmDelete: "Eliminare questa valutazione? L'azione resta tracciata nel registro audit.",
  dashNewAssessment: "+ Nuova valutazione",
  dashNeedLogin: "Accedi per vedere le tue valutazioni salvate.",
  dashSavedOn: "Salvata il",
  dashUpdatedOn: "aggiornata il",
  loadErr: "Impossibile caricare la valutazione richiesta.",
};

export type CheckerUi = typeof it;

const en: CheckerUi = {
  kicker: "AI Act Compliance Checker · beta",
  introTitle: "Classify the AI Act risk of one of your systems, in 10 minutes.",
  introBody:
    "A guided questionnaire leads you to a risk classification under Regulation (EU) 2024/1689 (AI Act), with a checklist of applicable obligations, gaps and an action plan. Every result cites its legal basis: no generative AI involved, only verifiable deterministic rules.",
  introBullets: [
    "One AI system at a time (repeat for each system).",
    "Your answers stay in your browser until you choose to save them to your account.",
    "Updated to the Digital Omnibus changes (June 2026), with warnings where not yet in the Official Journal.",
  ],
  start: "Start the assessment",
  stepLabel: (n, total) => `Step ${n} of ${total}`,
  back: "← Back",
  next: "Next",
  seeResult: "See the result",
  backHome: "← ComplyAI",
  myAssessments: "My assessments →",

  s1Title: "The system and your role",
  s1Name: "Name of the AI system (as you call it internally)",
  s1NamePh: "E.g. AI CV screening, customer support chatbot…",
  s1Desc: "What it does, in one sentence (optional)",
  s1RoleLegend: "What is your company's role for this system?",
  s1RoleNote: "Definitions: Art. 3, points 3–4 AI Act. Your role determines which obligations apply.",
  roles: {
    deployer: { label: "We use it (deployer)", desc: "We use an AI system developed by others, under our authority." },
    provider: { label: "We develop/provide it (provider)", desc: "We develop the system and place it on the market or into service under our name/trademark (including internal use)." },
    both: { label: "Both", desc: "We developed it and we use it ourselves." },
  },

  s2Title: "Prohibited practices",
  s2Body: "Does the system perform any of these practices? They have been prohibited since 2 February 2025 (Art. 5 AI Act), regardless of anything else.",
  s2None: "None of these practices",

  s3Title: "Regulated products (Annex I)",
  s3Body: "Is the system a product — or a safety component of a product — already covered by EU harmonised legislation (medical devices, toys, lifts, radio equipment, vehicles, machinery…)?",
  annexI: {
    no: { label: "No", desc: "The system is not part of products covered by EU product legislation." },
    sectionA: { label: "Yes, a regulated product", desc: "E.g. medical device, toy, lift, radio equipment (Annex I, sec. A)." },
    machinery: { label: "Yes, machinery", desc: "Product covered by the Machinery Regulation (EU) 2023/1230 — special regime post-Omnibus." },
    unsure: { label: "I don't know", desc: "We will flag it for verification: it changes deadlines and obligations." },
  },
  s3Carveout: "The AI only performs assistance, optimisation, convenience or quality-control functions",
  s3CarveoutDesc: "…and a malfunction would not endanger health or safety (narrowed definition of ‘safety component’, Omnibus).",

  s4Title: "High-risk use cases (Annex III)",
  s4Body: "Is the system used in any of these areas? (Obligations from 2 December 2027, unless a derogation applies — next step.)",
  s4None: "None of these areas",

  s5Title: "Possible derogations (Art. 6(3))",
  s5Body: "An Annex III system may not be high-risk if one of these conditions applies. Careful: it is a self-assessment you must document, and profiling always rules it out.",
  s5None: "No applicable condition",
  s5Profiling: "The system profiles natural persons",
  s5ProfilingDesc: "Automated evaluation of personal aspects (performance, reliability, interests, behaviour…). If yes, the derogation never applies (Art. 6(3), last subparagraph).",

  s6Title: "Transparency (Art. 50)",
  s6Body: "These obligations apply from 2 August 2026 and the Omnibus did NOT postpone them. Does the system fall under any of these cases?",
  s6None: "None of these cases",

  s7Title: "Last question and summary",
  s7Gpai: "We develop a general-purpose AI model (GPAI)",
  s7GpaiDesc: "I.e. a foundation model (e.g. an LLM you trained) provided to third parties — rare for an SME: using ChatGPT/Claude does not make you a GPAI provider.",
  s7Summary: "Summary of answers",
  s7System: "System",
  s7Unnamed: "(unnamed)",
  s7Role: "Role",
  s7Prohibited: "Prohibited practices selected",
  s7CarveoutShort: "(non-safety functions only)",
  s7Areas: "Annex III areas",
  s7Exemptions: "6(3) derogations",
  s7Profiling: "Profiling",
  s7Transparency: "Art. 50 transparency cases",
  yes: "yes",
  no: "no",

  reportTitle: "ComplyAI — AI System Risk Assessment Report",
  generatedOn: "Generated on",
  evaluatedSystem: "The assessed system",
  roleLabel: "Role",
  bothRoles: "provider and deployer",
  whyTitle: "Why this result",
  deadlinesTitle: "Dates that matter to you",
  thWhen: "When",
  thWhat: "What",
  thSource: "Source",
  pendingGu: "Pending publication in the EU Official Journal",
  checklistTitle: "Obligations checklist",
  checklistHint: "Mark the current status of each obligation: gaps and the action plan update accordingly.",
  dueBy: "by",
  alreadyApplicable: "already applicable",
  planTitle: (n) => `Action plan (${n} items)`,
  planEmpty: "No gaps: all obligations are compliant or not applicable.",
  ownerLabel: "Owner",
  ownerPh: "E.g. IT manager, HR, owner…",
  dueLabel: "Internal deadline",
  duePh: "E.g. 30/09/2026",
  warningsTitle: "Warnings",
  reportFooterNote: "* = date stemming from the Omnibus, pending publication in the EU Official Journal.",
  sourcesNote: "Regulatory content:",
  printBtn: "Print / save PDF",
  jsonBtn: "Download data (JSON)",
  restartBtn: "New assessment",

  levels: {
    prohibited: "Prohibited practice",
    high: "High risk",
    transparency: "Limited risk — transparency obligations",
    minimal: "Minimal risk",
  },
  statuses: {
    ok: "Compliant",
    partial: "Partial",
    missing: "Missing",
    unknown: "To assess",
    na: "Not applicable",
  },

  saveTitle: "Save to your account",
  saveHint: "Free. Find your assessments again, update them, and every change lands in the audit log.",
  saveBtn: "Save this assessment",
  updateBtn: "Update saved assessment",
  savedOk: "Saved ✓ — find it under “My assessments”.",
  saveErr: "Save failed:",
  notConfigured: "Saving will be available shortly (backend being configured). Meanwhile use Print/PDF or JSON.",
  authEmail: "Email",
  authPassword: "Password (min 6 characters)",
  authSignIn: "Sign in",
  authSignUp: "Sign up",
  authOr: "or",
  authHint: "No confirmation email during the beta: sign up and you're in.",
  authErr: "Authentication failed:",
  signOut: "Sign out",
  loading: "Loading…",

  dashTitle: "My assessments",
  dashEmpty: "No saved assessments. Complete the questionnaire and save it from the report.",
  dashOpen: "Open",
  dashDelete: "Delete",
  dashConfirmDelete: "Delete this assessment? The action remains tracked in the audit log.",
  dashNewAssessment: "+ New assessment",
  dashNeedLogin: "Sign in to see your saved assessments.",
  dashSavedOn: "Saved on",
  dashUpdatedOn: "updated on",
  loadErr: "Could not load the requested assessment.",
};

const packs: Record<Locale, CheckerUi> = { it, en };

export function getUi(locale: Locale): CheckerUi {
  return packs[locale];
}
